[package]
name = "minilibx-rs"
version = "0.1.0"
edition = "2021"
links = "X11"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
xlib = []

[dependencies]
libc = "0.2.28"
x11 = "2.19.1"